/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) throws InstantiationException, IllegalAccessException, ClassNotFoundException {
    	if (args.length != 1) {
    		System.err.printf("Error: Wrong number of args");
    		System.out.printf("Use: App <dayNumber>");
    		System.exit(1);
    	}
    	int dayNumber = Integer.valueOf(args[0]);
    	String className = String.format("Day%d", dayNumber);
    	Runnable runner = (Runnable)App.class.getClassLoader().loadClass(className).newInstance();
    	runner.run();
    }
}
